<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>override_v5</name>
  <version>0.0.0</version>
  <description>Simulating the VEX v5 game Override</description>
  <maintainer email="kmhswimgirl@gmail.com">Kylie Herbstzuber</maintainer>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <build_depend>geometry_msgs</build_depend>
  <exec_depend>geometry_msgs</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <!-- <exec_depend>vex_interfaces</exec_depend>
  <build_depend>vex_interfaces</build_depend>
  <build_export_depend>vex_interfaces</build_export_depend> -->

  <export>
    <build_type>ament_cmake</build_type>
    <gazebo_ros gazebo_model_path="${prefix}/models"/>
    <gazebo_ros gazebo_model_path="${prefix}/worlds"/>
    <gazebo_ros gazebo_model_path="${prefix}"/>
  </export>
</package>